SomaSaldoDevedor = 
SUMX (
    VALUES ( BASE_HISTORICA[BAS_CPF_CNPJ] ),
    CALCULATE (
        FIRSTNONBLANK ( BASE_HISTORICA[BAS_SALDO_DEVEDOR], 1 ),
        FILTER (
            BASE_HISTORICA,
            BASE_HISTORICA[BAS_CPF_CNPJ] = EARLIER ( BASE_HISTORICA[BAS_CPF_CNPJ] )
        )
    )
)
